books/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import include, path

from books import views

app_name = "books"
urlpatterns = [
    path("read/", views.read, name="read"),
    path("books/", views.BookListView.as_view(), name="list"),
    path(
        "books/my/", login_required(views.OwnBookListView.as_view()), name="list_mine"
    ),
    path("book/create/", views.CreateView.as_view(), name="create"),  # FIXME:
    path("books/toread/", views.ToReadView.as_view(), name="toread"),
    path("books/<int:pk>/", views.BookDetailView.as_view(), name="detail"),  # FIXME:
    path("stats/", views.stats, name="stats"),
    path(
        "ajax/get_last_page_read_by_book_name/",
        views.get_last_page_read_by_book_name,
        name="get_last_page_read_by_book_name",
    ),
    path("start_reading/<int:book_pk>/", views.start_reading, name="start_reading"),
    path("", views.home, name="home"),
]

booktracker/urls.py
import django.contrib.auth.urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import PasswordChangeView
from django.urls import include, path

from books import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("profile/", views.profile, name="profile"),
    path("signup/", views.signup, name="signup"),
    path("", include("books.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

books/models.py
import datetime

from django.contrib.auth.models import AbstractUser, User
from django.db import models
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from django.db.models import Max


class Author(models.Model):
    name = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.name


class BookCategory(models.Model):
    category = models.CharField(max_length=50, unique=True)

    class Meta:
        verbose_name_plural = "Book categories"

    def __str__(self):
        return self.category


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, null=True)
    pages_total = models.PositiveSmallIntegerField(null=True)
    image = models.ImageField(upload_to="covers", null=True, blank=True)
    image_url = models.CharField(null=True, max_length=1000)
    categories = models.ManyToManyField(BookCategory, blank=True)
    added_by = models.ForeignKey(
        "ReadingUser", on_delete=models.CASCADE, null=True
    )  # FIXME:remove null=True after adding authorship to all books

    class Meta:
        unique_together = ("title", "author")

    def __str__(self):
        return f"{self.title} - {self.author}"


class ReadingUser(models.Model):  # TODO:rename to reader
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    books = models.ManyToManyField(Book, through="UserBook")

    def __str__(self):
        return f"{self.user}"

    def is_day_done(self, date):
        days = ReadingDay.objects.filter(
            user_book__reading_user=self, datetime__date=date
        )
        return days.count() > 0

    def is_today_done(self):
        return (
            ReadingDay.objects.filter(
                user_book__reading_user__pk=self.pk,
                datetime__date=datetime.date.today(),
            ).count()
            > 0
        )

    def get_chain_length(self):
        length = 0
        iterdate = datetime.date.today()
        if self.is_today_done():
            length += 1

        delta = datetime.timedelta(days=1)
        iterdate -= delta
        while self.is_day_done(iterdate):
            length += 1
            iterdate -= delta
        return length

    def add_book(self, book):
        self.books.add(book)

    def get_book_list_for_select_field(self):
        userbook_list = UserBook.objects.filter(reading_user__user=self.user)
        book_list = [i.book for i in userbook_list]
        choices = [(i.id, i.title) for i in book_list]
        return choices


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        ReadingUser.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.readinguser.save()


class UserBook(models.Model):
    reading_user = models.ForeignKey(ReadingUser, on_delete=models.CASCADE, null=True)
    book = models.ForeignKey(Book, on_delete=models.CASCADE, null=True)
    last_page_read = models.PositiveSmallIntegerField(default=0)
    start_read_date = models.DateField(auto_now=True)
    end_date_read = models.DateField(auto_now_add=True)
    review = models.TextField()

    class Meta:
        unique_together = ("reading_user", "book")

    def __str__(self):
        username = None
        title = None
        try:
            username = self.reading_user.user.username
        except:
            username = "username"
        try:
            title = self.book.title
        except:
            title = "title"
        return f"{username} reads {title}"

    def read_today(self, last_page_read, time_read=None):
        today = datetime.date.today()
        ReadingDay.objects.create(
            user_book=self,
            datetime=today,
            last_page_read=last_page_read,
            time_read=time_read,
        )

    @property
    def progress(self):
        if not self.book.pages_total:
            return None
        if not self.last_page_read:
            return None
        return round(self.last_page_read / self.book.pages_total * 100)

    READ = "READ"
    WANT_TO_READ = "WANT TO READ"
    CURRENTLY_READING = "CURRENTLY READING"

    @property
    def status(self):
        if self.last_page_read == 0:
            return self.WANT_TO_READ
        if self.last_page_read >= self.book.pages_total:
            return self.READ
        return self.CURRENTLY_READING


class ReadingDay(models.Model):
    user_book = models.ForeignKey(UserBook, on_delete=models.CASCADE)
    datetime = models.DateTimeField()
    last_page_read = models.PositiveSmallIntegerField(default=0)
    time_read = models.IntegerField(default=0, null=True)
    pages_read = models.PositiveSmallIntegerField(default=0)

    def __str__(self):
        return f"{self.user_book.reading_user} read til {self.last_page_read} pages of {self.user_book.book} on {self.datetime}"

    def get_user(self):
        return self.user_book.reading_user

    def get_book(self):
        return self.user_book.book

    def save(self, *args, **kwargs):
        self.user_book.last_page_read = self.last_page_read
        self.user_book.save()

        reading_day = (
            ReadingDay.objects.filter(user_book=self.user_book)
            .order_by("-datetime")
            .first()
        )
        if reading_day:
            past_last_page_read = reading_day.last_page_read
        else:
            past_last_page_read = 0

        self.pages_read = self.last_page_read - past_last_page_read

        super().save(*args, **kwargs)


class Note(models.Model):
    userbook = models.ForeignKey(UserBook, on_delete=models.CASCADE)
    text = models.TextField()

    def __str__(self):
        return f"{self.text}"

    # def save(self, *args, **kwargs):
    #     super().save(*args, **kwargs)

books/views.py
from django import forms
from django.contrib import messages
from django.contrib.auth import authenticate, login, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm, UserCreationForm
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.db.models import Max, Q, F
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import (
    get_list_or_404,
    get_object_or_404,
    redirect,
    render,
    reverse,
)
from django.urls import reverse_lazy
from django.utils import timezone
from django.views import generic

from books.calendar_widget import Calendar
from books.forms import BookForm, ReadBookForm
from books.models import Author, Book, Note, ReadingDay, ReadingUser, UserBook
from books.utils import get_cover_image

from books.models import BookCategory


def get_reading_user(user):
    return ReadingUser.objects.filter(user=user).first()


def home(request):
    if request.user.is_authenticated:
        timenow = timezone.now()
        year = timenow.year
        month = timenow.month
        calendar = Calendar(request.user, year, month).formatmonth()

        if request.user.is_authenticated:
            reading_user = get_reading_user(request.user)
            today_done = reading_user.is_today_done()
            chain_length = reading_user.get_chain_length()
        else:
            today_done = False
            chain_length = 0

        return render(
            request,
            "books/home.html",
            {
                "calendar": calendar,
                "today_done": today_done,
                "chain_length": chain_length,
            },
        )
    else:
        return render(request, "books/cover.html")


@login_required
def read(request):
    if request.method == "GET":
        reading_user = get_reading_user(request.user)

        choices = reading_user.get_book_list_for_select_field()
        book_select_field = forms.ChoiceField(widget=forms.Select, choices=choices)

        today_done = reading_user.is_today_done()
        chain_length = reading_user.get_chain_length()

        last_page_read = None
        if len(choices):
            book = Book.objects.get(pk=choices[0][0])
            userbook = UserBook.objects.get(reading_user=reading_user, book=book)
            last_page_read = userbook.last_page_read

        form = ReadBookForm(initial={"last_page_read": last_page_read})
        form.fields["id"].choices = choices

        return render(
            request,
            "books/read_form.html",
            {
                "book_list": book_select_field,
                "today_done": today_done,
                "chain_length": chain_length,
                "form": form,
            },
        )
    else:
        book_id = request.POST.get("id")
        last_page_read = int(request.POST.get("last_page_read"))
        time_read = int(request.POST.get("time_read"))

        mark_as_read_today(request.user, book_id, last_page_read, time_read)

        return redirect("books:home")


def mark_as_read_today(user, book_id, last_page_read, time_read):
    reading_user = ReadingUser.objects.get(user=user)
    userbook = UserBook.objects.get(reading_user__user=user, book__id=book_id)
    userbook.read_today(last_page_read, time_read)


@login_required
def get_last_page_read_by_book_name(request):
    id = request.GET["id"]
    book = get_object_or_404(Book, id=id)
    readinguser = ReadingUser.objects.get(user=request.user)
    userbook = UserBook.objects.get(reading_user=readinguser, book=book)
    last_page_read = userbook.last_page_read
    data = {"last_page_read": last_page_read}
    return JsonResponse(data)


# TODO:remove this. leave only `my books` page created by me
class BookListView(generic.ListView):
    model = Book
    template_name = "books/list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if self.request.user.is_authenticated:
            context["today_done"] = ReadingUser.objects.get(
                user=self.request.user
            ).is_today_done()
        else:
            context["today_done"] = True
            # TODO:rename today_done -> show_read_today_banner

        category = self.request.GET.get("category")
        if category:
            # FIXME:change to self.object_list
            context["book_list"] = Book.objects.filter(categories__category=category)
        else:
            context["book_list"] = Book.objects.all()

        context["categories"] = BookCategory.objects.all()

        return context


class OwnBookListView(generic.ListView):
    model = UserBook
    template_name = "books/list_mine.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            reading_user = get_reading_user(self.request.user)
            context["today_done"] = reading_user.is_today_done()
            context["chain_length"] = reading_user.get_chain_length()

            reading_list = self.object_list.filter(
                reading_user__user=self.request.user
            ).values_list("book", flat=True)

            category = self.request.GET.get("category")
            book_list = Book.objects.all()
            if category:
                book_list = Book.objects.filter(categories__category=category)

            # book_list = book_list.filter(pk__in=reading_list)

            book_list = book_list.filter(
                Q(added_by__isnull=True) | Q(added_by=reading_user)
            )  # FIXME: remove Q(added_by=None) part when all books have authors

            # FIXME:
            # context["book_list"] = book_list #FIXME:change this to this style
            context["book_list"] = [
                {
                    "title": book.title,
                    "image": book.image,
                    "image_url": book.image_url,
                    "pk": book.id,
                    "author": book.author,
                    "progress": get_reading_progress(self.request.user, book.title),
                }
                for i, book in enumerate(book_list)
            ]

            context["categories"] = BookCategory.objects.all()

        return context


def get_reading_progress(user, book_title):
    user_book = UserBook.objects.filter(
        Q(reading_user__user=user), Q(book__title=book_title)
    ).first()
    if not user_book:
        return None
    return user_book.progress


class BookDetailView(generic.UpdateView):
    template_name = "books/detail.html"
    model = UserBook

    def get(self, request, *args, **kwargs):
        pk = kwargs["pk"]
        book = get_object_or_404(Book, pk=pk)

        today_done = None
        review = None
        note_list = None
        last_page_read_form = None
        reading_status = None

        if request.user.is_authenticated:
            userbook = UserBook.objects.filter(
                reading_user=get_reading_user(request.user), book__title=book.title
            ).first()

            if userbook:
                last_page_read = userbook.last_page_read
                note_list = userbook.note_set.all().values_list(("text"), flat=True)
                review = userbook.review  # TODO:make review a model
                reading_user = get_reading_user(request.user)
                today_done = reading_user.is_today_done()
                reading_status = userbook.status

        return render(
            request,
            self.template_name,
            {
                "title": book.title,
                "author": book.author,
                "pages_total": book.pages_total,
                "cover_src": book.image_url,
                "today_done": today_done,
                "book_pk": book.id,
                "reading_status": reading_status,
                "note_list": note_list,
                "review": review,
            },
        )

    def post(self, request, *args, **kwargs):
        pk = kwargs["pk"]
        book = get_object_or_404(Book, pk=pk)

        userbook, created = UserBook.objects.get_or_create(
            reading_user__user=request.user, book=book
        )

        last_page_read = request.POST.get("last_page_read", None)
        if last_page_read is not None:
            userbook.last_page_read = last_page_read
            userbook.save()

        newnote = request.POST.get("newnote", None)
        if newnote:
            newnote = Note.objects.create(userbook=userbook, text=newnote)
            userbook.note_set.add(newnote)

        review = request.POST.get("review", None)
        if review:
            userbook.review = review
            userbook.save()

        return redirect("books:detail", pk=pk)


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            raw_password = form.cleaned_data["password1"]
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect("books:home")
    else:
        form = UserCreationForm()
    return render(request, "registration/signup.html", {"form": form})


def profile(request):
    return render(request, "books/profile.html", {})


def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, "Password successfully changed.")
            return redirect("password_change_done")
        else:
            messages.error(request, "Please correct the error below")
    else:
        form = PasswordChangeForm(request.user)

books/templates/books/cover.html
{% extends 'base.html' %}

{% block content %}
<div class="text-center cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <h1 class="m-4 cover-heading">booktracker</h1>
  <p class="lead">the only website you need to track your reads. </p>
  <p class="lead">sign up, make it a habit, keep it for life.</p>
</div>
{% endblock %}

books/templates/books/create_book_form.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}Create book{% endblock %}

{% block content %}
<div class="container">
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-dark btn-lg" type="submit" value="Submit">
    </form>
</div>
{% endblock %}

{% block javascript %}
<script src="{% static 'books/create.js' %}"></script>
{% endblock %}

books/templates/books/detail.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% if last_page_read_form is None %}
        <h2><a class="btn btn-light " href="{% url 'books:start_reading' book_pk=book_pk %}">start reading this book!</a></h2>
        {% endif %}
        <table class="table table-sm table-borderless col-5">
        <tbody>
            <tr><td>title: </td><td> {{ title }}</td></tr>
            <tr><td>author: </td><td> {{ author|default_if_none:"unknown" }}</td></tr>
            <tr><td>pages total: </td><td> {{ pages_total|default_if_none:"unknown" }}</td></tr>
            <tr><td>reading status: </td><td> {{ reading_status|default:"want to read" }}</td></tr>
        </tbody>
        </table>

        <img class="img-fluid" alt="cover" src="{{ cover_src }}" data-holder-rendered="true" style="height: 225px; display: block;">

        {% if user.is_authenticated %}
        <div>
            <label>notes (private)</label>
            {% for note in note_list %}
            <div >{{ note }}</div>
            {% endfor %}

            <div>
                <div><input type="text" class="m-1" name="newnote" id="newnote" /></div>
                <button class="btn btn-dark">save</button>
            </div>
        </div>
        {% endif %}

        {{ review_list }}

        {% if user.is_authenticated %}
        <label for="review">review (public)</label>
        <div>
            <textarea type="text" name="review" value="{{ review }}" rows="4" cols="50"></textarea>
        </div>
        <button class="btn btn-dark">publish</button>
        {% endif %}
        <!-- TODO:move newnote,review to form -->
    </form>
</div>
{% endblock %}

books/templates/books/footer.html
<footer class="footer py-3">
    <div class="container">
        <span class="text-muted"><strong>booktracker</strong> by
            <a href="https://t.me/valeriykundas">Valerii Kundas</a>
        </span>
    </div>
</footer>

books/templates/books/hero.html
{% if user.is_authenticated %}
    {% if not today_done %}
        <div class="container jumbotron">
            <div class="">
                <h1 class="display-5">don't break the chain!</h1>
                <p class="lead">read today and make it {{chain_length|add:"1" }} consecutive reading
                    day{{chain_length|add:"1"|pluralize}}</p>
                <hr class="my-4">
                <a class="btn btn-light" href="{% url 'books:read' %}" role="button">i have read today!</a>
            </div>
        </div>
    {% endif %}
{% endif %}

books/templates/books/home.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-8 align-middle" style="margin: auto">
            <h2 class="m-5">chain length - {{ chain_length }}</h2>
            {{ calendar }}
        </div>
    </div>
</div>
{% endblock %}

books/templates/books/list.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="container">
    {% comment %} {% if user.is_authenticated %}
    <a class="btn btn-md btn-light" href="{% url 'books:create' %}" role="button">add new book</a>
    {% endif %} {% endcomment %}

    <div class="container m-4">
        {% for category in categories %}
        <a class="btn btn-light" href="{% url 'books:list' %}?category={{category}}">{{ category }}</a>
        {% endfor %}
    </div>

    <div class="row">
        {% for book in book_list %}
        <div class="col col-md-4">
            <div class="card mb-4">
                <a href="{% url 'books:detail' book.pk %}">
                    {% comment %} {% if book.image_url %} {% endcomment %}
                    <img class="card-img-top" alt="cover" src="{{ book.image_url }}" data-holder-rendered="true"
                        style="height: 225px; width: 100%; display: block;">
                    {% comment %} {% else %}
                    <img class="card-img-top" alt="cover" data-holder-rendered="true"
                        style="height: 225px; width: 100%; display: block;">
                    {% endif %} {% endcomment %}
                </a>

                <div class="card-body text-center">
                    <a href={% url 'books:detail' book.pk %} class="text-dark">
                        <h4 class="card-text">{{book.title}}</h4>
                    </a>
                    <h6 class="card-text text-secondary">{{ book.author|default_if_none:"" }}</h6>
                    
                    {% comment %} {% if user.is_authenticated %}
                    <div class="progress">
                        <div class="progress-bar bg-success" role="progressbar" style="width: {{book.progress}}%">
                            {{ book.progress }}%</div>
                    </div>
                    {% endif %} {% endcomment %}
                </div>
            </div>
        </div>
        {% empty %}
        No books yet in the database.
        {% endfor %}
    </div>
</div>
{% endblock %}

books/templates/books/list_mine.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="container">
    {% comment %} {% if user.is_authenticated %}
    <div class="container mb-4">
        <a class="btn btn-md btn-light" href="{% url 'books:create' %}" role="button">add new book</a>
    </div>
    {% endif %} {% endcomment %}

    <div class="container m-4">
        {% for category in categories %}
        <a class="btn btn-light" href="{% url 'books:list_mine' %}?category={{category}}">{{ category }}</a>
        {% endfor %}
    </div>

    <div class="row">
        {% for book in book_list %}
        <div class="col col-md-4">
            <div class="card mb-4">
                <a href="{% url 'books:detail' book.pk %}">
                    {% comment %} {% if book.image_url %} {% endcomment %}
                    <img class="card-img-top" alt="cover" src="{{ book.image_url }}" data-holder-rendered="true"
                        style="height: 225px; width: 100%; display: block;">
                    {% comment %} {% else %}
                    <img class="card-img-top" alt="cover" data-holder-rendered="true"
                        style="height: 225px; width: 100%; display: block;">
                    {% endif %} {% endcomment %}
                </a>

                <div class="card-body text-center">
                    <a href={% url 'books:detail' book.pk %} class="text-dark">
                        <h4 class="card-text">{{book.title}}</h4>
                    </a>
                    <h6 class="card-text text-secondary">{{ book.author|default_if_none:"" }}</h6>
                    
                    {% if user.is_authenticated %}
                    <div class="progress">
                        <div class="progress-bar bg-warning" role="progressbar" style="width: {{ book.progress|default:0 }}%">
                            <span class="text-dark font-weight-bold">{{ book.progress|default:0 }}%</span>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
        {% empty %}
        No books yet in the database.
        {% endfor %}
    </div>
</div>
{% endblock %}

books/templates/books/menu.html
<nav class="navbar navbar-expand-md navbar-light">
    <a class="navbar-brand" href="{% url 'books:home' %}">booktracker</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#NavBar" aria-controls="NavBar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="NavBar">
        <div class="navbar-nav mr-auto">
            {% if user.is_authenticated%}
            <a class="nav-item nav-link pl-3" href="{% url 'books:read' %}">i have read today</a>
            {% endif %}
            {% comment %} <a class="nav-item nav-link" href="{% url 'books:list' %}">books</a> {% endcomment %}

            {% if user.is_authenticated%}
            <a class="nav-item nav-link pl-3" href="{% url 'books:list_mine' %}">books</a>
            <a class="nav-item nav-link pl-3" href="{% url 'books:stats' %}">stats</a>
            <a class="nav-item nav-link pl-3" href="{% url 'books:create' %}">add book</a>
            {% endif %}
        </div>

        <div class="navbar-nav justify-content-end">
            {% if user.is_authenticated %}
            <a class="nav-item nav-link pl-3" href="{% url 'profile' %}">{{user.username}}</a>
            <a class="nav-item nav-link pl-3" href="{% url 'logout' %}">logout</a>
            {% else %}
            <a class="nav-item nav-link pl-3" href="{% url 'login' %}">login</a>
            <a class="nav-item nav-link pl-3" href="{% url 'signup' %}">signup</a>
            {% endif %}
        </div>
    </div>
</nav>

books/templates/books/profile.html
{% extends 'base.html' %}

{% load static %}

{% block hero %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-4">
            <a href="{% url 'password_change' %}">Change password</a>
        </div>
    </div>
</div>
{% endblock %}

books/templates/books/read_form.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <form action=" {% url 'books:read' %}" method="post" book-progress-url="{% url 'books:get_last_page_read_by_book_name' %}">
        {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-dark" type="submit" value="Submit" />
    </form>
</div>
{% endblock %}

{% block javascript %}
<script src="{% static 'books/read.js' %}"></script>
{% endblock %}

books/templates/books/stats.html
{% extends 'base.html' %}


{% block content %}
{% for day in days %}
<div>{{day.datetime}} - last page read {{day.last_page_read}} - pages reads {{ day.pages_read }} - {{ day.time_read }} minutes - {{day.user_book.book}}</div>
{% endfor %}
{% endblock content %}

books/templates/books/toread_list.html
{% extends 'base.html' %}

{% block content %}

<body class="vsc-initialized">
    <main role="main">
        <div class="album py-5 bg-light">
            <div class="container">
                {% comment %} {% if user.is_authenticated %}
                <a class="btn btn-warning btn-lg" href="{% url 'books:create' %}" role="button">Add new book</a>
                {% endif %} {% endcomment %}

                <div class="row">
                    {% if book_list %}
                    {% for book in book_list %}
                    <div class="col-md-4">
                        <div class="card mb-4 shadow-sm">
                            <a href="{% url 'books:detail' book.pk %}">
                                <img class="card-img-top" alt="cover" src="/media/{{book.image}}"
                                    data-holder-rendered="true" style="height: 225px; width: 100%; display: block;">
                            </a>

                            <div class="card-body">
                                <a href={% url 'books:detail' book.pk %} class="text-dark">
                                    <h4 class="card-text">{{book.title}}</h4>
                                </a>
                                <h6 class="card-text text-secondary">{{book.author}}</h6>

                                {% if user.is_authenticated and book.progress %}
                                <div class="progress">
                                    <div class="progress-bar bg-success" role="progressbar"
                                        style="width: {{book.progress}}%">
                                        {{ book.progress }}%</div>
                                </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    {% else %}
                    <div class="col-md-4">
                        Your to read list is empty.
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </main>
    {% endblock %}